sudo: false

language: python

# Run each tox environment separately
matrix:
  include:
    - name: "Python 2.7 Unit Test"
      python: '2.7'
      env: TOX_ENV=py27
    - name: "Python 3.5 Unit Test"
      python: '3.5'
      env: TOX_ENV=py35
    - name: "Python 3.6 Unit Test"
      python: '3.6'
      env: TOX_ENV=py36
    - name: "Python 3.7 Unit Test"
      python: '3.7'
      env: TOX_ENV=py37
    - name: "Python 3.8 Unit Test"
      python: '3.8'
      env: TOX_ENV=py38
    - name: "Docs"
      python: 2.7
      env: TOX_ENV=docs

addons:
  apt:
    packages:
    - asciidoc
    - jpegoptim
    - libfreetype6-dev
    - libjpeg-progs
    - libjpeg8-dev
    - liblcms2-dev
    - libpcre3-dev
    - libtiff5-dev
    - libwebp-dev
    - libxml2-dev
    - libxslt1-dev
    - nodejs
    - optipng
    - python-tk
    - tcl8.5-dev
    - tk8.5-dev
    - zlib1g-dev

# Cache pip requirements for faster builds
cache:
  directories:
    - $HOME/.cache/pip

install:
  # JS dependencies
  - npm install sass@0.5.0 requirejs@2.1 stylus@0.54.6 uglify-js@2.4.23 less@2.7.3

  # Python test requirements
  - pip install tox

before_script:
  - export PATH=${TRAVIS_BUILD_DIR}/node_modules/.bin/:${PATH}
  - export PYTHONPATH=${PYTHONPATH}:/usr/share/asciidoc/

script:
  - tox -e $TOX_ENV